var units={"3":{"unitname":"Hitpoints","displayname":"HP"},
"4":{"unitname":"Mass","displayname":"kg"},
"6":{"unitname":"capacitor units","displayname":"GJ"},
"9":{"unitname":"Hitpoints","displayname":"HP"},
"11":{"unitname":"MegaWatts","displayname":"MW"},
"12":{"unitname":"Fitting slots","displayname":""},
"13":{"unitname":"Fitting slots","displayname":""},
"14":{"unitname":"Fitting slots","displayname":""},
"15":{"unitname":"MegaWatts","displayname":"MW"},
"18":{"unitname":"capacitor units","displayname":"GJ"},
"20":{"unitname":"Modifier Relative Percent","displayname":"%"},
"30":{"unitname":"MegaWatts","displayname":"MW"},
"37":{"unitname":"Acceleration","displayname":"m/sec"},
"38":{"unitname":"Volume","displayname":"m3"},
"39":{"unitname":"Percentage","displayname":"%"},
"48":{"unitname":"Teraflops","displayname":"tf"},
"49":{"unitname":"Teraflops","displayname":"tf"},
"50":{"unitname":"Teraflops","displayname":"tf"},
"51":{"unitname":"Milliseconds","displayname":"s"},
"54":{"unitname":"Length","displayname":"m"},
"55":{"unitname":"Milliseconds","displayname":"s"},
"64":{"unitname":"Multiplier","displayname":"x"},
"66":{"unitname":"Percentage","displayname":"%"},
"67":{"unitname":"capacitor units","displayname":"GJ"},
"68":{"unitname":"Hitpoints","displayname":"HP"},
"70":{"unitname":"Multiplier","displayname":"x"},
"72":{"unitname":"Hitpoints","displayname":"HP"},
"73":{"unitname":"Milliseconds","displayname":"s"},
"76":{"unitname":"Length","displayname":"m"},
"77":{"unitname":"Volume","displayname":"m3"},
"79":{"unitname":"Milliseconds","displayname":"s"},
"80":{"unitname":"Acceleration","displayname":"m/sec"},
"83":{"unitname":"Hitpoints","displayname":"HP"},
"84":{"unitname":"Hitpoints","displayname":"HP"},
"87":{"unitname":"Length","displayname":"m"},
"90":{"unitname":"attributePoints","displayname":"points"},
"91":{"unitname":"Length","displayname":"m"},
"97":{"unitname":"capacitor units","displayname":"GJ"},
"98":{"unitname":"Length","displayname":"m"},
"99":{"unitname":"Length","displayname":"m"},
"101":{"unitname":"Hardpoints","displayname":"hardpoints"},
"102":{"unitname":"Hardpoints","displayname":"hardpoints"},
"103":{"unitname":"Length","displayname":"m"},
"107":{"unitname":"Length","displayname":"m"},
"108":{"unitname":"Length","displayname":"m"},
"109":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"110":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"111":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"113":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"114":{"unitname":"Hitpoints","displayname":"HP"},
"116":{"unitname":"Hitpoints","displayname":"HP"},
"117":{"unitname":"Hitpoints","displayname":"HP"},
"118":{"unitname":"Hitpoints","displayname":"HP"},
"120":{"unitname":"Modifier Percent","displayname":"%"},
"121":{"unitname":"MegaWatts","displayname":"MW"},
"125":{"unitname":"Length","displayname":"m"},
"126":{"unitname":"Length","displayname":"m"},
"128":{"unitname":"Sizeclass","displayname":"1=small 2=medium 3=l"},
"130":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"131":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"132":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"133":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"134":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"137":{"unitname":"groupID","displayname":"groupID"},
"138":{"unitname":"Hitpoints","displayname":"HP"},
"139":{"unitname":"Hitpoints","displayname":"HP"},
"140":{"unitname":"Hitpoints","displayname":"HP"},
"141":{"unitname":"Hitpoints","displayname":"HP"},
"142":{"unitname":"Length","displayname":"m"},
"143":{"unitname":"Length","displayname":"m"},
"144":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"145":{"unitname":"Modifier Percent","displayname":"%"},
"146":{"unitname":"Modifier Percent","displayname":"%"},
"147":{"unitname":"Modifier Percent","displayname":"%"},
"148":{"unitname":"Modifier Percent","displayname":"%"},
"149":{"unitname":"Modifier Percent","displayname":"%"},
"150":{"unitname":"Modifier Percent","displayname":"%"},
"151":{"unitname":"Percentage","displayname":"%"},
"154":{"unitname":"Length","displayname":"m"},
"158":{"unitname":"Length","displayname":"m"},
"160":{"unitname":"Radians/Second","displayname":"rad/sec"},
"161":{"unitname":"Volume","displayname":"m3"},
"164":{"unitname":"attributePoints","displayname":"points"},
"165":{"unitname":"attributePoints","displayname":"points"},
"166":{"unitname":"attributePoints","displayname":"points"},
"167":{"unitname":"attributePoints","displayname":"points"},
"168":{"unitname":"attributePoints","displayname":"points"},
"169":{"unitname":"realPercent","displayname":"%"},
"175":{"unitname":"attributePoints","displayname":"points"},
"176":{"unitname":"attributePoints","displayname":"points"},
"177":{"unitname":"attributePoints","displayname":"points"},
"178":{"unitname":"attributePoints","displayname":"points"},
"179":{"unitname":"attributePoints","displayname":"points"},
"180":{"unitname":"attributeID","displayname":"attributeID"},
"181":{"unitname":"attributeID","displayname":"attributeID"},
"182":{"unitname":"typeID","displayname":"typeID"},
"183":{"unitname":"typeID","displayname":"typeID"},
"184":{"unitname":"typeID","displayname":"typeID"},
"191":{"unitname":"Bonus","displayname":"+"},
"197":{"unitname":"Length","displayname":"m"},
"202":{"unitname":"Modifier Percent","displayname":"%"},
"204":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"208":{"unitname":"attributePoints","displayname":"points"},
"209":{"unitname":"attributePoints","displayname":"points"},
"210":{"unitname":"attributePoints","displayname":"points"},
"211":{"unitname":"attributePoints","displayname":"points"},
"212":{"unitname":"Multiplier","displayname":"x"},
"213":{"unitname":"Modifier Percent","displayname":"%"},
"216":{"unitname":"Percentage","displayname":"%"},
"235":{"unitname":"Bonus","displayname":"+"},
"236":{"unitname":"Bonus","displayname":"+"},
"237":{"unitname":"Modifier Percent","displayname":"%"},
"242":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"243":{"unitname":"Multiplier","displayname":"x"},
"244":{"unitname":"Multiplier","displayname":"x"},
"252":{"unitname":"Modifier Percent","displayname":"%"},
"263":{"unitname":"Hitpoints","displayname":"HP"},
"265":{"unitname":"Hitpoints","displayname":"HP"},
"267":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"268":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"269":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"270":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"271":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"272":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"273":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"274":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"275":{"unitname":"Multiplier","displayname":"x"},
"281":{"unitname":"Milliseconds","displayname":"s"},
"282":{"unitname":"Multiplier","displayname":"x"},
"283":{"unitname":"Volume","displayname":"m3"},
"292":{"unitname":"Percentage","displayname":"%"},
"293":{"unitname":"Percentage","displayname":"%"},
"294":{"unitname":"realPercent","displayname":"%"},
"306":{"unitname":"Modifier Percent","displayname":"%"},
"308":{"unitname":"Percentage","displayname":"%"},
"309":{"unitname":"Percentage","displayname":"%"},
"310":{"unitname":"Percentage","displayname":"%"},
"311":{"unitname":"Bonus","displayname":"+"},
"312":{"unitname":"realPercent","displayname":"%"},
"313":{"unitname":"Percentage","displayname":"%"},
"314":{"unitname":"Percentage","displayname":"%"},
"315":{"unitname":"realPercent","displayname":"%"},
"317":{"unitname":"Percentage","displayname":"%"},
"318":{"unitname":"Percentage","displayname":"%"},
"319":{"unitname":"Modifier Relative Percent","displayname":"%"},
"321":{"unitname":"Time","displayname":"sec"},
"323":{"unitname":"Percentage","displayname":"%"},
"327":{"unitname":"Percentage","displayname":"%"},
"330":{"unitname":"Milliseconds","displayname":"s"},
"331":{"unitname":"Slot","displayname":"Slot"},
"335":{"unitname":"Percentage","displayname":"%"},
"336":{"unitname":"Multiplier","displayname":"x"},
"337":{"unitname":"realPercent","displayname":"%"},
"338":{"unitname":"Percentage","displayname":"%"},
"349":{"unitname":"Percentage","displayname":"%"},
"351":{"unitname":"Percentage","displayname":"%"},
"362":{"unitname":"Percentage","displayname":"%"},
"379":{"unitname":"Percentage","displayname":"%"},
"399":{"unitname":"Percentage","displayname":"%"},
"403":{"unitname":"Percentage","displayname":"%"},
"405":{"unitname":"Percentage","displayname":"%"},
"418":{"unitname":"Percentage","displayname":"%"},
"420":{"unitname":"realPercent","displayname":"%"},
"422":{"unitname":"Level","displayname":"Level"},
"424":{"unitname":"Percentage","displayname":"%"},
"426":{"unitname":"Modifier Percent","displayname":"%"},
"432":{"unitname":"Percentage","displayname":"%"},
"434":{"unitname":"Percentage","displayname":"%"},
"435":{"unitname":"Bonus","displayname":"+"},
"436":{"unitname":"Percentage","displayname":"%"},
"437":{"unitname":"Percentage","displayname":"%"},
"438":{"unitname":"Percentage","displayname":"%"},
"440":{"unitname":"Percentage","displayname":"%"},
"441":{"unitname":"realPercent","displayname":"%"},
"444":{"unitname":"Percentage","displayname":"%"},
"447":{"unitname":"Percentage","displayname":"%"},
"450":{"unitname":"Bonus","displayname":"+"},
"451":{"unitname":"Percentage","displayname":"%"},
"452":{"unitname":"Percentage","displayname":"%"},
"453":{"unitname":"Percentage","displayname":"%"},
"455":{"unitname":"Percentage","displayname":"%"},
"458":{"unitname":"Length","displayname":"m"},
"459":{"unitname":"Length","displayname":"m"},
"460":{"unitname":"Percentage","displayname":"%"},
"468":{"unitname":"Percentage","displayname":"%"},
"470":{"unitname":"Milliseconds","displayname":"s"},
"472":{"unitname":"typeID","displayname":"typeID"},
"479":{"unitname":"Milliseconds","displayname":"s"},
"480":{"unitname":"Length","displayname":"m"},
"482":{"unitname":"capacitor units","displayname":"GJ"},
"505":{"unitname":"Time","displayname":"sec"},
"506":{"unitname":"Milliseconds","displayname":"s"},
"507":{"unitname":"typeID","displayname":"typeID"},
"508":{"unitname":"Speed","displayname":"m/sec"},
"509":{"unitname":"Length","displayname":"m"},
"510":{"unitname":"Length","displayname":"m"},
"511":{"unitname":"realPercent","displayname":"%"},
"513":{"unitname":"Time","displayname":"sec"},
"514":{"unitname":"Length","displayname":"m"},
"516":{"unitname":"typeID","displayname":"typeID"},
"517":{"unitname":"Multiplier","displayname":"x"},
"544":{"unitname":"Milliseconds","displayname":"s"},
"545":{"unitname":"Milliseconds","displayname":"s"},
"546":{"unitname":"typeID","displayname":"typeID"},
"547":{"unitname":"Percentage","displayname":"%"},
"548":{"unitname":"realPercent","displayname":"%"},
"549":{"unitname":"MegaWatts","displayname":"MW"},
"550":{"unitname":"realPercent","displayname":"%"},
"552":{"unitname":"Length","displayname":"m"},
"554":{"unitname":"Modifier Relative Percent","displayname":"%"},
"555":{"unitname":"Percentage","displayname":"%"},
"556":{"unitname":"Milliseconds","displayname":"s"},
"557":{"unitname":"realPercent","displayname":"%"},
"559":{"unitname":"Mass","displayname":"kg"},
"560":{"unitname":"Milliseconds","displayname":"s"},
"564":{"unitname":"Millimeters","displayname":"mm"},
"565":{"unitname":"Modifier Percent","displayname":"%"},
"566":{"unitname":"Percentage","displayname":"%"},
"567":{"unitname":"Newton","displayname":"N"},
"582":{"unitname":"Milliseconds","displayname":"s"},
"584":{"unitname":"Length","displayname":"m"},
"591":{"unitname":"Percentage","displayname":"%"},
"596":{"unitname":"realPercent","displayname":"%"},
"600":{"unitname":"Multiplier","displayname":"x"},
"601":{"unitname":"Percentage","displayname":"%"},
"602":{"unitname":"groupID","displayname":"groupID"},
"603":{"unitname":"groupID","displayname":"groupID"},
"604":{"unitname":"groupID","displayname":"groupID"},
"605":{"unitname":"groupID","displayname":"groupID"},
"606":{"unitname":"groupID","displayname":"groupID"},
"608":{"unitname":"Modifier Percent","displayname":"%"},
"609":{"unitname":"groupID","displayname":"groupID"},
"610":{"unitname":"groupID","displayname":"groupID"},
"611":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"614":{"unitname":"realPercent","displayname":"%"},
"616":{"unitname":"Percentage","displayname":"%"},
"619":{"unitname":"Percentage","displayname":"%"},
"620":{"unitname":"Length","displayname":"m"},
"621":{"unitname":"Speed","displayname":"m/sec"},
"622":{"unitname":"Mass","displayname":"kg"},
"624":{"unitname":"Percentage","displayname":"%"},
"633":{"unitname":"Level","displayname":"Level"},
"643":{"unitname":"Time","displayname":"sec"},
"645":{"unitname":"Multiplier","displayname":"x"},
"646":{"unitname":"Multiplier","displayname":"x"},
"648":{"unitname":"Hitpoints","displayname":"HP"},
"650":{"unitname":"Length","displayname":"m"},
"651":{"unitname":"Length","displayname":"m"},
"652":{"unitname":"Modifier Percent","displayname":"%"},
"653":{"unitname":"Speed","displayname":"m/sec"},
"654":{"unitname":"Length","displayname":"m"},
"660":{"unitname":"Hitpoints","displayname":"HP"},
"665":{"unitname":"Length","displayname":"m"},
"666":{"unitname":"groupID","displayname":"groupID"},
"667":{"unitname":"groupID","displayname":"groupID"},
"668":{"unitname":"groupID","displayname":"groupID"},
"669":{"unitname":"Milliseconds","displayname":"s"},
"670":{"unitname":"Length","displayname":"m"},
"672":{"unitname":"Modifier Percent","displayname":"%"},
"676":{"unitname":"Milliseconds","displayname":"s"},
"677":{"unitname":"Milliseconds","displayname":"s"},
"680":{"unitname":"Length","displayname":"m"},
"681":{"unitname":"typeID","displayname":"typeID"},
"682":{"unitname":"typeID","displayname":"typeID"},
"683":{"unitname":"typeID","displayname":"typeID"},
"684":{"unitname":"Volume","displayname":"m3"},
"685":{"unitname":"Volume","displayname":"m3"},
"686":{"unitname":"Volume","displayname":"m3"},
"691":{"unitname":"Milliseconds","displayname":"s"},
"694":{"unitname":"typeID","displayname":"typeID"},
"695":{"unitname":"typeID","displayname":"typeID"},
"696":{"unitname":"typeID","displayname":"typeID"},
"697":{"unitname":"typeID","displayname":"typeID"},
"698":{"unitname":"typeID","displayname":"typeID"},
"699":{"unitname":"Volume","displayname":"m3"},
"700":{"unitname":"Volume","displayname":"m3"},
"701":{"unitname":"Volume","displayname":"m3"},
"703":{"unitname":"Volume","displayname":"m3"},
"704":{"unitname":"Volume","displayname":"m3"},
"705":{"unitname":"typeID","displayname":"typeID"},
"706":{"unitname":"typeID","displayname":"typeID"},
"707":{"unitname":"typeID","displayname":"typeID"},
"709":{"unitname":"typeID","displayname":"typeID"},
"711":{"unitname":"Length","displayname":"m"},
"712":{"unitname":"Percentage","displayname":"%"},
"713":{"unitname":"typeID","displayname":"typeID"},
"714":{"unitname":"Units","displayname":"units"},
"715":{"unitname":"Length","displayname":"m"},
"717":{"unitname":"Multiplier","displayname":"x"},
"719":{"unitname":"Milliseconds","displayname":"s"},
"720":{"unitname":"Volume","displayname":"m3"},
"722":{"unitname":"Milliseconds","displayname":"s"},
"726":{"unitname":"Volume","displayname":"m3"},
"728":{"unitname":"Percentage","displayname":"%"},
"750":{"unitname":"Percentage","displayname":"%"},
"751":{"unitname":"Percentage","displayname":"%"},
"752":{"unitname":"Percentage","displayname":"%"},
"753":{"unitname":"Percentage","displayname":"%"},
"754":{"unitname":"Percentage","displayname":"%"},
"755":{"unitname":"Percentage","displayname":"%"},
"756":{"unitname":"Percentage","displayname":"%"},
"757":{"unitname":"Percentage","displayname":"%"},
"760":{"unitname":"Percentage","displayname":"%"},
"761":{"unitname":"Percentage","displayname":"%"},
"762":{"unitname":"Percentage","displayname":"%"},
"764":{"unitname":"Percentage","displayname":"%"},
"766":{"unitname":"Percentage","displayname":"%"},
"767":{"unitname":"Percentage","displayname":"%"},
"769":{"unitname":"Percentage","displayname":"%"},
"770":{"unitname":"Percentage","displayname":"%"},
"776":{"unitname":"Percentage","displayname":"%"},
"777":{"unitname":"Percentage","displayname":"%"},
"778":{"unitname":"Percentage","displayname":"%"},
"780":{"unitname":"Percentage","displayname":"%"},
"781":{"unitname":"groupID","displayname":"groupID"},
"782":{"unitname":"Multiplier","displayname":"x"},
"783":{"unitname":"Absolute Percent","displayname":"%"},
"784":{"unitname":"Hitpoints","displayname":"HP"},
"785":{"unitname":"capacitor units","displayname":"GJ"},
"786":{"unitname":"Boolean","displayname":"1=True 0=False"},
"787":{"unitname":"Length","displayname":"m"},
"788":{"unitname":"Length","displayname":"m"},
"789":{"unitname":"Volume","displayname":"m3"},
"790":{"unitname":"typeID","displayname":"typeID"},
"792":{"unitname":"Percentage","displayname":"%"},
"796":{"unitname":"Mass","displayname":"kg"},
"797":{"unitname":"Length","displayname":"m"},
"799":{"unitname":"Multiplier","displayname":"x"},
"800":{"unitname":"Absolute Percent","displayname":"%"},
"802":{"unitname":"Multiplier","displayname":"x"},
"806":{"unitname":"Percentage","displayname":"%"},
"815":{"unitname":"attributePoints","displayname":"points"},
"816":{"unitname":"attributePoints","displayname":"points"},
"817":{"unitname":"attributePoints","displayname":"points"},
"818":{"unitname":"attributePoints","displayname":"points"},
"828":{"unitname":"Percentage","displayname":"%"},
"832":{"unitname":"Percentage","displayname":"%"},
"833":{"unitname":"realPercent","displayname":"%"},
"838":{"unitname":"Multiplier","displayname":"x"},
"841":{"unitname":"Length","displayname":"m"},
"842":{"unitname":"groupID","displayname":"groupID"},
"843":{"unitname":"groupID","displayname":"groupID"},
"844":{"unitname":"Length","displayname":"m"},
"846":{"unitname":"Percentage","displayname":"%"},
"847":{"unitname":"Percentage","displayname":"%"},
"848":{"unitname":"Percentage","displayname":"%"},
"850":{"unitname":"realPercent","displayname":"%"},
"851":{"unitname":"Modifier Relative Percent","displayname":"%"},
"854":{"unitname":"Boolean","displayname":"1=True 0=False"},
"857":{"unitname":"Percentage","displayname":"%"},
"858":{"unitname":"Modifier Percent","displayname":"%"},
"859":{"unitname":"Modifier Percent","displayname":"%"},
"861":{"unitname":"Boolean","displayname":"1=True 0=False"},
"863":{"unitname":"Multiplier","displayname":"x"},
"864":{"unitname":"Multiplier","displayname":"x"},
"865":{"unitname":"Length","displayname":"m"},
"866":{"unitname":"typeID","displayname":"typeID"},
"867":{"unitname":"Light Year","displayname":"ly"},
"868":{"unitname":"Units","displayname":"units"},
"870":{"unitname":"Percentage","displayname":"%"},
"871":{"unitname":"Percentage","displayname":"%"},
"884":{"unitname":"Percentage","displayname":"%"},
"885":{"unitname":"Units","displayname":"units"},
"894":{"unitname":"Percentage","displayname":"%"},
"895":{"unitname":"Percentage","displayname":"%"},
"896":{"unitname":"Percentage","displayname":"%"},
"897":{"unitname":"Percentage","displayname":"%"},
"898":{"unitname":"Absolute Percent","displayname":"%"},
"899":{"unitname":"Percentage","displayname":"%"},
"902":{"unitname":"realPercent","displayname":"%"},
"908":{"unitname":"Volume","displayname":"m3"},
"912":{"unitname":"Volume","displayname":"m3"},
"958":{"unitname":"Percentage","displayname":"%"},
"964":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"965":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"966":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"967":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"969":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"970":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"971":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"972":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"973":{"unitname":"Percentage","displayname":"%"},
"974":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"975":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"976":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"977":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"983":{"unitname":"Length","displayname":"m"},
"984":{"unitname":"Modifier Relative Percent","displayname":"%"},
"985":{"unitname":"Modifier Relative Percent","displayname":"%"},
"986":{"unitname":"Percentage","displayname":"%"},
"987":{"unitname":"Modifier Relative Percent","displayname":"%"},
"994":{"unitname":"Percentage","displayname":"%"},
"995":{"unitname":"Percentage","displayname":"%"},
"996":{"unitname":"Percentage","displayname":"%"},
"997":{"unitname":"Percentage","displayname":"%"},
"1002":{"unitname":"Milliseconds","displayname":"s"},
"1005":{"unitname":"capacitor units","displayname":"GJ"},
"1014":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1027":{"unitname":"Percentage","displayname":"%"},
"1028":{"unitname":"Percentage","displayname":"%"},
"1029":{"unitname":"Percentage","displayname":"%"},
"1030":{"unitname":"Percentage","displayname":"%"},
"1031":{"unitname":"Sizeclass","displayname":"1=small 2=medium 3=l"},
"1034":{"unitname":"Milliseconds","displayname":"s"},
"1035":{"unitname":"Milliseconds","displayname":"s"},
"1045":{"unitname":"Speed","displayname":"m/sec"},
"1073":{"unitname":"realPercent","displayname":"%"},
"1074":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1076":{"unitname":"realPercent","displayname":"%"},
"1079":{"unitname":"Percentage","displayname":"%"},
"1082":{"unitname":"Percentage","displayname":"%"},
"1083":{"unitname":"realPercent","displayname":"%"},
"1084":{"unitname":"realPercent","displayname":"%"},
"1087":{"unitname":"Slot","displayname":"Slot"},
"1089":{"unitname":"Absolute Percent","displayname":"%"},
"1090":{"unitname":"Absolute Percent","displayname":"%"},
"1091":{"unitname":"Absolute Percent","displayname":"%"},
"1092":{"unitname":"Absolute Percent","displayname":"%"},
"1093":{"unitname":"Absolute Percent","displayname":"%"},
"1094":{"unitname":"Percentage","displayname":"%"},
"1095":{"unitname":"Percentage","displayname":"%"},
"1096":{"unitname":"Percentage","displayname":"%"},
"1097":{"unitname":"Percentage","displayname":"%"},
"1098":{"unitname":"Percentage","displayname":"%"},
"1099":{"unitname":"Percentage","displayname":"%"},
"1104":{"unitname":"Percentage","displayname":"%"},
"1105":{"unitname":"Percentage","displayname":"%"},
"1106":{"unitname":"Percentage","displayname":"%"},
"1107":{"unitname":"Percentage","displayname":"%"},
"1108":{"unitname":"Percentage","displayname":"%"},
"1109":{"unitname":"Percentage","displayname":"%"},
"1110":{"unitname":"Percentage","displayname":"%"},
"1111":{"unitname":"Percentage","displayname":"%"},
"1112":{"unitname":"Multiplier","displayname":"x"},
"1113":{"unitname":"attributePoints","displayname":"points"},
"1123":{"unitname":"Milliseconds","displayname":"s"},
"1125":{"unitname":"Percentage","displayname":"%"},
"1126":{"unitname":"Percentage","displayname":"%"},
"1130":{"unitname":"Percentage","displayname":"%"},
"1131":{"unitname":"Percentage","displayname":"%"},
"1132":{"unitname":"attributePoints","displayname":"points"},
"1136":{"unitname":"attributePoints","displayname":"points"},
"1137":{"unitname":"Fitting slots","displayname":""},
"1138":{"unitname":"Percentage","displayname":"%"},
"1139":{"unitname":"Percentage","displayname":"%"},
"1141":{"unitname":"Percentage","displayname":"%"},
"1142":{"unitname":"Percentage","displayname":"%"},
"1143":{"unitname":"Percentage","displayname":"%"},
"1144":{"unitname":"Percentage","displayname":"%"},
"1145":{"unitname":"Percentage","displayname":"%"},
"1146":{"unitname":"Percentage","displayname":"%"},
"1147":{"unitname":"Percentage","displayname":"%"},
"1148":{"unitname":"Percentage","displayname":"%"},
"1149":{"unitname":"Percentage","displayname":"%"},
"1150":{"unitname":"Percentage","displayname":"%"},
"1151":{"unitname":"Percentage","displayname":"%"},
"1154":{"unitname":"Hardpoints","displayname":"hardpoints"},
"1155":{"unitname":"attributePoints","displayname":"points"},
"1156":{"unitname":"Percentage","displayname":"%"},
"1159":{"unitname":"Hitpoints","displayname":"HP"},
"1160":{"unitname":"Percentage","displayname":"%"},
"1164":{"unitname":"Percentage","displayname":"%"},
"1165":{"unitname":"Length","displayname":"m"},
"1167":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1169":{"unitname":"attributePoints","displayname":"points"},
"1181":{"unitname":"Percentage","displayname":"%"},
"1186":{"unitname":"Percentage","displayname":"%"},
"1187":{"unitname":"Percentage","displayname":"%"},
"1188":{"unitname":"Percentage","displayname":"%"},
"1189":{"unitname":"Percentage","displayname":"%"},
"1190":{"unitname":"Percentage","displayname":"%"},
"1191":{"unitname":"Percentage","displayname":"%"},
"1192":{"unitname":"Percentage","displayname":"%"},
"1193":{"unitname":"Percentage","displayname":"%"},
"1194":{"unitname":"Percentage","displayname":"%"},
"1201":{"unitname":"Percentage","displayname":"%"},
"1202":{"unitname":"Percentage","displayname":"%"},
"1203":{"unitname":"Percentage","displayname":"%"},
"1204":{"unitname":"Percentage","displayname":"%"},
"1205":{"unitname":"Percentage","displayname":"%"},
"1206":{"unitname":"Percentage","displayname":"%"},
"1208":{"unitname":"Percentage","displayname":"%"},
"1209":{"unitname":"Multiplier","displayname":"x"},
"1210":{"unitname":"Percentage","displayname":"%"},
"1211":{"unitname":"Hitpoints","displayname":"HP"},
"1212":{"unitname":"Level","displayname":"Level"},
"1213":{"unitname":"Percentage","displayname":"%"},
"1214":{"unitname":"Length","displayname":"m"},
"1216":{"unitname":"Percentage","displayname":"%"},
"1217":{"unitname":"Percentage","displayname":"%"},
"1218":{"unitname":"Percentage","displayname":"%"},
"1219":{"unitname":"Percentage","displayname":"%"},
"1220":{"unitname":"Percentage","displayname":"%"},
"1221":{"unitname":"trueTime","displayname":"sec"},
"1222":{"unitname":"Percentage","displayname":"%"},
"1223":{"unitname":"Percentage","displayname":"%"},
"1225":{"unitname":"Percentage","displayname":"%"},
"1226":{"unitname":"Percentage","displayname":"%"},
"1227":{"unitname":"Percentage","displayname":"%"},
"1228":{"unitname":"Percentage","displayname":"%"},
"1229":{"unitname":"Percentage","displayname":"%"},
"1230":{"unitname":"Percentage","displayname":"%"},
"1231":{"unitname":"Percentage","displayname":"%"},
"1233":{"unitname":"Volume","displayname":"m3"},
"1234":{"unitname":"Percentage","displayname":"%"},
"1235":{"unitname":"Percentage","displayname":"%"},
"1236":{"unitname":"Percentage","displayname":"%"},
"1245":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1252":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1255":{"unitname":"Percentage","displayname":"%"},
"1256":{"unitname":"Percentage","displayname":"%"},
"1263":{"unitname":"Absolute Percent","displayname":"%"},
"1270":{"unitname":"Percentage","displayname":"%"},
"1271":{"unitname":"Drone bandwidth","displayname":"Mbit/sec"},
"1272":{"unitname":"Drone bandwidth","displayname":"Mbit/sec"},
"1274":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"1282":{"unitname":"Multiplier","displayname":"x"},
"1284":{"unitname":"Multiplier","displayname":"x"},
"1285":{"unitname":"typeID","displayname":"typeID"},
"1289":{"unitname":"typeID","displayname":"typeID"},
"1290":{"unitname":"typeID","displayname":"typeID"},
"1291":{"unitname":"Multiplier","displayname":"x"},
"1292":{"unitname":"Multiplier","displayname":"x"},
"1293":{"unitname":"Multiplier","displayname":"x"},
"1294":{"unitname":"realPercent","displayname":"%"},
"1295":{"unitname":"Percentage","displayname":"%"},
"1296":{"unitname":"Percentage","displayname":"%"},
"1298":{"unitname":"groupID","displayname":"groupID"},
"1299":{"unitname":"groupID","displayname":"groupID"},
"1300":{"unitname":"groupID","displayname":"groupID"},
"1301":{"unitname":"groupID","displayname":"groupID"},
"1302":{"unitname":"typeID","displayname":"typeID"},
"1303":{"unitname":"typeID","displayname":"typeID"},
"1304":{"unitname":"typeID","displayname":"typeID"},
"1305":{"unitname":"typeID","displayname":"typeID"},
"1306":{"unitname":"Multiplier","displayname":"x"},
"1307":{"unitname":"Multiplier","displayname":"x"},
"1308":{"unitname":"Multiplier","displayname":"x"},
"1309":{"unitname":"Multiplier","displayname":"x"},
"1310":{"unitname":"Percentage","displayname":"%"},
"1313":{"unitname":"Percentage","displayname":"%"},
"1314":{"unitname":"Percentage","displayname":"%"},
"1315":{"unitname":"Percentage","displayname":"%"},
"1316":{"unitname":"Percentage","displayname":"%"},
"1317":{"unitname":"Length","displayname":"m"},
"1320":{"unitname":"Percentage","displayname":"%"},
"1321":{"unitname":"Percentage","displayname":"%"},
"1322":{"unitname":"Percentage","displayname":"%"},
"1323":{"unitname":"Percentage","displayname":"%"},
"1324":{"unitname":"Percentage","displayname":"%"},
"1325":{"unitname":"Percentage","displayname":"%"},
"1326":{"unitname":"Percentage","displayname":"%"},
"1327":{"unitname":"Percentage","displayname":"%"},
"1328":{"unitname":"Multiplier","displayname":"x"},
"1329":{"unitname":"Drone bandwidth","displayname":"Mbit/sec"},
"1332":{"unitname":"Percentage","displayname":"%"},
"1334":{"unitname":"Speed","displayname":"m/sec"},
"1351":{"unitname":"typeID","displayname":"typeID"},
"1352":{"unitname":"groupID","displayname":"groupID"},
"1355":{"unitname":"Percentage","displayname":"%"},
"1356":{"unitname":"Percentage","displayname":"%"},
"1357":{"unitname":"Percentage","displayname":"%"},
"1358":{"unitname":"Percentage","displayname":"%"},
"1359":{"unitname":"Percentage","displayname":"%"},
"1360":{"unitname":"Percentage","displayname":"%"},
"1361":{"unitname":"Percentage","displayname":"%"},
"1368":{"unitname":"Bonus","displayname":"+"},
"1369":{"unitname":"Bonus","displayname":"+"},
"1370":{"unitname":"Astronomical Unit","displayname":"AU"},
"1371":{"unitname":"attributePoints","displayname":"points"},
"1372":{"unitname":"Astronomical Unit","displayname":"AU"},
"1373":{"unitname":"Multiplier","displayname":"x"},
"1374":{"unitname":"Bonus","displayname":"+"},
"1375":{"unitname":"Bonus","displayname":"+"},
"1376":{"unitname":"Bonus","displayname":"+"},
"1377":{"unitname":"Teraflops","displayname":"tf"},
"1378":{"unitname":"MegaWatts","displayname":"MW"},
"1379":{"unitname":"Acceleration","displayname":"m/sec"},
"1380":{"unitname":"typeID","displayname":"typeID"},
"1382":{"unitname":"Time","displayname":"sec"},
"1383":{"unitname":"Mass","displayname":"kg"},
"1384":{"unitname":"Mass","displayname":"kg"},
"1385":{"unitname":"Mass","displayname":"kg"},
"1416":{"unitname":"Milliseconds","displayname":"s"},
"1418":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1419":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1420":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1421":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1422":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1423":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1424":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1425":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"1426":{"unitname":"Absolute Percent","displayname":"%"},
"1427":{"unitname":"Absolute Percent","displayname":"%"},
"1428":{"unitname":"Absolute Percent","displayname":"%"},
"1429":{"unitname":"Absolute Percent","displayname":"%"},
"1453":{"unitname":"Percentage","displayname":"%"},
"1454":{"unitname":"Milliseconds","displayname":"s"},
"1456":{"unitname":"Percentage","displayname":"%"},
"1458":{"unitname":"Milliseconds","displayname":"s"},
"1459":{"unitname":"Modifier Percent","displayname":"%"},
"1460":{"unitname":"attributePoints","displayname":"points"},
"1462":{"unitname":"Modifier Percent","displayname":"%"},
"1464":{"unitname":"Length","displayname":"m"},
"1465":{"unitname":"Modifier Relative Percent","displayname":"%"},
"1466":{"unitname":"Modifier Relative Percent","displayname":"%"},
"1467":{"unitname":"Modifier Relative Percent","displayname":"%"},
"1468":{"unitname":"Modifier Relative Percent","displayname":"%"},
"1469":{"unitname":"Multiplier","displayname":"x"},
"1470":{"unitname":"Multiplier","displayname":"x"},
"1471":{"unitname":"Multiplier","displayname":"x"},
"1472":{"unitname":"Multiplier","displayname":"x"},
"1473":{"unitname":"Multiplier","displayname":"x"},
"1474":{"unitname":"Multiplier","displayname":"x"},
"1475":{"unitname":"Multiplier","displayname":"x"},
"1476":{"unitname":"Multiplier","displayname":"x"},
"1477":{"unitname":"Multiplier","displayname":"x"},
"1478":{"unitname":"Multiplier","displayname":"x"},
"1479":{"unitname":"Multiplier","displayname":"x"},
"1480":{"unitname":"Multiplier","displayname":"x"},
"1481":{"unitname":"Multiplier","displayname":"x"},
"1482":{"unitname":"Multiplier","displayname":"x"},
"1483":{"unitname":"Multiplier","displayname":"x"},
"1484":{"unitname":"Multiplier","displayname":"x"},
"1485":{"unitname":"Multiplier","displayname":"x"},
"1486":{"unitname":"Multiplier","displayname":"x"},
"1487":{"unitname":"Multiplier","displayname":"x"},
"1488":{"unitname":"Multiplier","displayname":"x"},
"1489":{"unitname":"Percentage","displayname":"%"},
"1490":{"unitname":"Percentage","displayname":"%"},
"1491":{"unitname":"Percentage","displayname":"%"},
"1492":{"unitname":"Percentage","displayname":"%"},
"1493":{"unitname":"Multiplier","displayname":"x"},
"1494":{"unitname":"Multiplier","displayname":"x"},
"1495":{"unitname":"Multiplier","displayname":"x"},
"1496":{"unitname":"Multiplier","displayname":"x"},
"1497":{"unitname":"Multiplier","displayname":"x"},
"1498":{"unitname":"Multiplier","displayname":"x"},
"1499":{"unitname":"Multiplier","displayname":"x"},
"1500":{"unitname":"Multiplier","displayname":"x"},
"1536":{"unitname":"Percentage","displayname":"%"},
"1547":{"unitname":"Sizeclass","displayname":"1=small 2=medium 3=l"},
"1549":{"unitname":"Volume","displayname":"m3"},
"1556":{"unitname":"Volume","displayname":"m3"},
"1557":{"unitname":"Volume","displayname":"m3"},
"1558":{"unitname":"Volume","displayname":"m3"},
"1559":{"unitname":"Volume","displayname":"m3"},
"1560":{"unitname":"Volume","displayname":"m3"},
"1561":{"unitname":"Volume","displayname":"m3"},
"1562":{"unitname":"Volume","displayname":"m3"},
"1563":{"unitname":"Volume","displayname":"m3"},
"1564":{"unitname":"Volume","displayname":"m3"},
"1573":{"unitname":"Volume","displayname":"m3"},
"1574":{"unitname":"Percentage","displayname":"%"},
"1575":{"unitname":"Percentage","displayname":"%"},
"1576":{"unitname":"Percentage","displayname":"%"},
"1577":{"unitname":"Percentage","displayname":"%"},
"1582":{"unitname":"Milliseconds","displayname":"s"},
"1583":{"unitname":"Level","displayname":"Level"},
"1584":{"unitname":"Level","displayname":"Level"},
"1590":{"unitname":"Length","displayname":"m"},
"1591":{"unitname":"Length","displayname":"m"},
"1595":{"unitname":"typeID","displayname":"typeID"},
"1597":{"unitname":"Hours","displayname":""},
"1598":{"unitname":"typeID","displayname":"typeID"},
"1599":{"unitname":"typeID","displayname":"typeID"},
"1601":{"unitname":"typeID","displayname":"typeID"},
"1603":{"unitname":"Money","displayname":"ISK"},
"1612":{"unitname":"Time","displayname":"sec"},
"1613":{"unitname":"Time","displayname":"sec"},
"1615":{"unitname":"Level","displayname":"Level"},
"1619":{"unitname":"Percentage","displayname":"%"},
"1631":{"unitname":"Logistical Capacity","displayname":"m3/hour"},
"1632":{"unitname":"typeID","displayname":"typeID"},
"1633":{"unitname":"MegaWatts","displayname":"MW"},
"1634":{"unitname":"Teraflops","displayname":"tf"},
"1638":{"unitname":"Money","displayname":"ISK"},
"1639":{"unitname":"Money","displayname":"ISK"},
"1640":{"unitname":"realPercent","displayname":"%"},
"1641":{"unitname":"realPercent","displayname":"%"},
"1643":{"unitname":"Time","displayname":"sec"},
"1644":{"unitname":"Length","displayname":"m"},
"1646":{"unitname":"Volume","displayname":"m3"},
"1647":{"unitname":"Hours","displayname":""},
"1651":{"unitname":"Absolute Percent","displayname":"%"},
"1653":{"unitname":"Volume","displayname":"m3"},
"1655":{"unitname":"Length","displayname":"m"},
"1671":{"unitname":"Modifier Percent","displayname":"%"},
"1674":{"unitname":"Modifier Percent","displayname":"%"},
"1675":{"unitname":"Modifier Percent","displayname":"%"},
"1676":{"unitname":"Modifier Percent","displayname":"%"},
"1686":{"unitname":"Modifier Relative Percent","displayname":"%"},
"1690":{"unitname":"Teraflops","displayname":"tf"},
"1691":{"unitname":"MegaWatts","displayname":"MW"},
"1766":{"unitname":"groupID","displayname":"groupID"},
"1770":{"unitname":"Volume","displayname":"m3"},
"1772":{"unitname":"Absolute Percent","displayname":"%"},
"1773":{"unitname":"Sex","displayname":"1=Male 2=Unisex 3=Female"},
"1775":{"unitname":"Percentage","displayname":"%"},
"1778":{"unitname":"Percentage","displayname":"%"},
"1782":{"unitname":"groupID","displayname":"groupID"},
"1783":{"unitname":"groupID","displayname":"groupID"},
"1785":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1794":{"unitname":"Percentage","displayname":"%"},
"1795":{"unitname":"Milliseconds","displayname":"s"},
"1798":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1799":{"unitname":"Multiplier","displayname":"x"},
"1802":{"unitname":"Percentage","displayname":"%"},
"1804":{"unitname":"Volume","displayname":"m3"},
"1806":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1811":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"1812":{"unitname":"Length","displayname":"m"},
"1813":{"unitname":"Length","displayname":"m"},
"1814":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"1815":{"unitname":"Inversed Modifier Percent","displayname":"%"},
"1816":{"unitname":"Percentage","displayname":"%"},
"1817":{"unitname":"Percentage","displayname":"%"},
"1820":{"unitname":"Money","displayname":"ISK"},
"1839":{"unitname":"Time","displayname":"sec"},
"1851":{"unitname":"Percentage","displayname":"%"},
"1854":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1855":{"unitname":"Length","displayname":"m"},
"1856":{"unitname":"Percentage","displayname":"%"},
"1872":{"unitname":"groupID","displayname":"groupID"},
"1879":{"unitname":"groupID","displayname":"groupID"},
"1880":{"unitname":"groupID","displayname":"groupID"},
"1881":{"unitname":"groupID","displayname":"groupID"},
"1886":{"unitname":"Multiplier","displayname":"x"},
"1890":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1892":{"unitname":"Hitpoints","displayname":"HP"},
"1893":{"unitname":"Hitpoints","displayname":"HP"},
"1894":{"unitname":"Modifier Percent","displayname":"%"},
"1895":{"unitname":"Modifier Percent","displayname":"%"},
"1896":{"unitname":"Modifier Percent","displayname":"%"},
"1897":{"unitname":"Modifier Percent","displayname":"%"},
"1904":{"unitname":"Money","displayname":"ISK"},
"1905":{"unitname":"Percentage","displayname":"%"},
"1906":{"unitname":"Percentage","displayname":"%"},
"1907":{"unitname":"Percentage","displayname":"%"},
"1908":{"unitname":"attributePoints","displayname":"points"},
"1912":{"unitname":"Units","displayname":"units"},
"1913":{"unitname":"typeID","displayname":"typeID"},
"1914":{"unitname":"Speed","displayname":"m/sec"},
"1916":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1917":{"unitname":"Time","displayname":"sec"},
"1920":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1923":{"unitname":"Percentage","displayname":"%"},
"1925":{"unitname":"Percentage","displayname":"%"},
"1927":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1928":{"unitname":"Units","displayname":"units"},
"1929":{"unitname":"Units","displayname":"units"},
"1930":{"unitname":"Percentage","displayname":"%"},
"1932":{"unitname":"Multiplier","displayname":"x"},
"1933":{"unitname":"Percentage","displayname":"%"},
"1935":{"unitname":"Percentage","displayname":"%"},
"1936":{"unitname":"Percentage","displayname":"%"},
"1937":{"unitname":"Percentage","displayname":"%"},
"1939":{"unitname":"Absolute Percent","displayname":"%"},
"1944":{"unitname":"typeID","displayname":"typeID"},
"1945":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1949":{"unitname":"Percentage","displayname":"%"},
"1952":{"unitname":"Multiplier","displayname":"x"},
"1954":{"unitname":"Multiplier","displayname":"x"},
"1958":{"unitname":"Boolean","displayname":"1=True 0=False"},
"1961":{"unitname":"Percentage","displayname":"%"},
"1966":{"unitname":"Multiplier","displayname":"x"},
"1967":{"unitname":"Multiplier","displayname":"x"},
"1968":{"unitname":"Multiplier","displayname":"x"},
"1969":{"unitname":"Multiplier","displayname":"x"},
"1971":{"unitname":"Multiplier","displayname":"x"},
"1972":{"unitname":"Multiplier","displayname":"x"},
"1978":{"unitname":"Percentage","displayname":"%"},
"1981":{"unitname":"Length","displayname":"m"},
"1982":{"unitname":"Percentage","displayname":"%"},
"1985":{"unitname":"Time","displayname":"sec"},
"2023":{"unitname":"Percentage","displayname":"%"},
"2024":{"unitname":"Percentage","displayname":"%"},
"2025":{"unitname":"Percentage","displayname":"%"},
"2026":{"unitname":"Percentage","displayname":"%"},
"2033":{"unitname":"Acceleration","displayname":"m/sec"},
"2034":{"unitname":"Hitpoints","displayname":"HP"},
"2035":{"unitname":"Hitpoints","displayname":"HP"},
"2036":{"unitname":"Hitpoints","displayname":"HP"},
"2037":{"unitname":"Hitpoints","displayname":"HP"},
"2038":{"unitname":"Hitpoints","displayname":"HP"},
"2039":{"unitname":"Hitpoints","displayname":"HP"},
"2044":{"unitname":"Length","displayname":"m"},
"2045":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"2055":{"unitname":"Volume","displayname":"m3"},
"2065":{"unitname":"groupID","displayname":"groupID"},
"2066":{"unitname":"Length","displayname":"m"},
"2067":{"unitname":"Length","displayname":"m"},
"2103":{"unitname":"typeID","displayname":"typeID"},
"2112":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"2113":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"2114":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"2115":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"2116":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"2135":{"unitname":"Inverse Absolute Percent","displayname":"%"},
"2136":{"unitname":"Percentage","displayname":"%"},
"2137":{"unitname":"Percentage","displayname":"%"},
"2138":{"unitname":"attributeID","displayname":"attributeID"},
"2139":{"unitname":"Percentage","displayname":"%"},
"2140":{"unitname":"Percentage","displayname":"%"},
"2141":{"unitname":"Percentage","displayname":"%"},
"2142":{"unitname":"Percentage","displayname":"%"},
"2143":{"unitname":"Percentage","displayname":"%"},
"2144":{"unitname":"realPercent","displayname":"%"},
"2145":{"unitname":"Percentage","displayname":"%"},
"2147":{"unitname":"Modifier Relative Percent","displayname":"%"},
"2148":{"unitname":"Modifier Relative Percent","displayname":"%"},
"2255":{"unitname":"Percentage","displayname":"%"},
"2256":{"unitname":"Percentage","displayname":"%"},
"2257":{"unitname":"Percentage","displayname":"%"},
"2258":{"unitname":"Percentage","displayname":"%"}};
